### ISSUE TITLE
Consolidate user assets implementation

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-api#223] opened 2023-02-21 17:48 UTC
Review #127 

Verify implications of images.smartcitizen.me being deprecated on patforms user profiles

https://images.smartcitizen.me/s100/avatars/b4b/1djs79t.earth.jpg
https://smartcitizen.me/users/6556

**Comment by timcowlishaw** [comment] 2023-10-27 07:15
Closing as a dupe of #166 - This should be partially dealt with in #271 with the remaining work to be done after i've updated smartcitizen-web to always use the new image.

**Closed by timcowlishaw** 2023-10-27 07:15 UTC
Labels: enhancement
