### ISSUE TITLE
User profile image urls

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-api#166] opened 2020-04-30 10:15 UTC
User profile JSON blob returned by `/v0/me`

```json
{
    "avatar": "https://images.smartcitizen.me/s100/avatars/b4b/1djs79t.lab.png",
    "devices": [],
    "email": "..",
    "id": 148,
    "joined_at": "2013-06-06T19:59:29Z",
    "legacy_api_key": "...",
    "location": {},
    "profile_picture": "http://api.smartcitizen.me/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBPZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d90982f085da9d5c2183c726d3245f51fa39cdc0/25a19eb09b28c28d77b99e5bda1b8d04_200x200.jpeg",
    "profile_picture2": "http://api.smartcitizen.me/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBPZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d90982f085da9d5c2183c726d3245f51fa39cdc0/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCam9MY21WemFYcGxTU0lNTVRBd2VERXdNQVk2QmtWVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--74c34520cbe1b1037fa838d7b2a3692d8db5b794/25a19eb09b28c28d77b99e5bda1b8d04_200x200.jpeg",
    "role": "admin",
    "updated_at": "2019-09-27T13:12:01Z",
    "url": "http://pral2a.com",
    "username": "pral2a",
    "uuid": "b4bb2a6f-c3ef-4964-bc79-e8d78f0e66d2"
}
```

1. User profile image urls in http causing the front-end to switch from http to https when loading the `profile_picture` or `profile_picture2`

![Screenshot 2020-04-30 at 11 55 48](https://user-images.githubusercontent.com/74249/80699386-2962cb00-8adc-11ea-9be8-6d1556821d19.png)

2. User profile contains the `avatar` property with a deprecated domain / service "https://images.smartcitizen.me/s100/avatars/b4b/1djs79t.lab.png"

3. Why we have `profile_picture` or `profile_picture2`? 

4. I suggest we clean this path or document it properly `/rails/active_storage/representations/`? 

_Topic 1 is critical, topics 2-4 are not urgent but will be useful to address them_

**Comment by viktorsmari** [comment] 2020-04-30 15:12
1. See pr #167 
2. `avatar` is the old attribute before we switched to use Active Storage.
  It is used as a fallback in the Angular app
```html
 <img ng-src="{{ vm.user.profile_picture || vm.user.avatar || './assets/images/avatar.svg' }}">
```
3. It was a test at the time, for using different size thumbnails if needed:
   It's not in use, so we can simply remove that one line, there is no other reference to it.

  https://github.com/fablabbcn/smartcitizen-api/blob/88f9a16288d9c6a4963136c1bb80d9658afe3102/app/views/v0/users/_user.jbuilder#L16-L17
4. This is a **rails** thing

**Comment by pral2a** [comment] 2020-05-04 11:23
1. OK
2. I suggest you work on it to clean things up
3. Yes, let's leave only one or at least document this properly on the api docs
4. Let's leave it as it is and we can see how Rails 6 follows with it

**Comment by pral2a** [comment] 2021-04-19 13:53
[upload.rb](https://github.com/fablabbcn/smartcitizen-api/blob/7ac0f044ce59137f2317db3dfdfcf3e503f37d2f/app/models/upload.rb) is deprecated. Consider removal on the upcoming refurbish

**Comment by oscgonfer** [comment] 2023-05-04 11:04
https://github.com/fablabbcn/smartcitizen-api/issues/223

**Comment by oscgonfer** [comment] 2023-07-20 08:35
Hi @timcowlishaw 

After reviewing https://github.com/fablabbcn/smartcitizen-api/pull/239, I feel we are missing something still. Is there a migration to do for this to work? Currently:

![imagen](https://github.com/fablabbcn/smartcitizen-api/assets/13301321/7b34f4e0-5ada-4ba7-8a4d-21efa6fcc71f)

**Comment by timcowlishaw** [comment] 2023-07-21 11:50
Hey @oscgonfer  - i've taken a look this morning, it appears to be unrelated to that PR, but definitely a related bug: `` profiles that used the old `avatar` property (pre-activestorage) rather than `profile_picture` don't show as the images.smartcitizen.me DNS record has gone away. Any idea where this used to point to? 

See for example https://images.smartcitizen.me/s100/avatars/701/1citvht.10407640_420278614786473_8707648267347732669_n.jpg on the profile https://smartcitizen.me/users/6028.

We would need to work out where that pointed to (an AWS bucket, i'm guessing?) and if the images still exist we could either:

 - resurrect that domain as a 'legacy' image host, and optionally do something in the rails app to deprecate that 'avatar property and ensure that 'profile_picture' either points to activestorage or to the images.sc host transparently.
 
 - Write a script to import all the old images as activestorage blobs then shut down images.sc and remove the avatar field (probably preferable).
 
 Any idea whereabouts the images might be, or where that DNS record originally pointed to?

**Comment by viktorsmari** [comment] 2023-07-25 08:54
There is a `smartcitizen-images` app on Heroku that has not been changed since 2015

The app appears to be down:
https://smartcitizen-images.herokuapp.com/

Here is the app on Heroku:
https://dashboard.heroku.com/apps/smartcitizen-images

It might need some updates

![image](https://github.com/fablabbcn/smartcitizen-api/assets/1689020/4e507850-e29d-436e-8b1a-ef241c3de215)


Last line from the log file:

> 2023-07-25T08:50:58.840090+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/favicon.ico" host=smartcitizen-images.herokuapp.com request_id=b87dcf47-f78d-4e0a-8716-879da28304ef fwd="46.22.107.156" dyno= connect= service= status=503 bytes= protocol=https

**Comment by timcowlishaw** [comment] 2023-08-10 09:40
Hi there @viktorsmari  - aha thanks for that - any idea where the source code for that lives, and would you be able to give me access to the repo, and to the application on heroku? I'll investigate further. Many thanks!

Tim

**Comment by viktorsmari** [comment] 2023-08-10 10:02
I did not find it here:
https://github.com/orgs/fablabbcn/repositories?language=&page=2&q=smartc&sort=&type=all

Maybe the code is hosted directly on Heroku, and not on Github?

Maybe @pral2a can give you access to the Heroku dashboard?

**Comment by pral2a** [comment] 2023-08-11 16:25
Hi @timcowlishaw @viktorsmari 

That was a middleware written in Node to abstract S3

I though that was fully deprecated in favour of Rails Active Storage Overview but maybe some legacies remain

I sent a tarball of the Heroku source

Thank! :)

**Comment by timcowlishaw** [comment] 2023-10-26 06:01
Finally looking at this, sorry folks.

We've got two related problems, as i see it:

1) None of the `avatars` are available publicly at their URL any more (due to that heroku app going offline) and somewhere in the front-end, the `avatar` takes precedence over the `profile_picture` when both are set, so eg in @pral2a's case, although he has a profile picture, it doesn't show because the (broken) avatar is displayed.

2) Several accounts (the majority of those that have any image set) have only the (deprecated, broken) avatar and no profile picture:

```
sc_dev=# select count(users.id), users.avatar_url is not null as has_avatar, active_storage_attachments.id is not null as has_profile_pic from users left join active_storage_attachments on active_storage_attachments.record_type='User' and active_storage_attachments.record_id=users.id group by has_avatar, has_profile_pic;
 count | has_avatar | has_profile_pic
-------+------------+-----------------
     6 | t          | t
  7463 | f          | f
   108 | f          | t
   357 | t          | f
(4 rows)
```

Therefore I think we need to tackle this in steps:

1) Update the front-end to remove any references to `avatar` and use the `profile_picture` consistently
2) Migrate all the old `avatar` images to the `profile_picture` field where no `profile_picture` already exists with a script to be run on prod (this can happen concurrently with (1) but the difference won't be seen 'til (1) is done.
3) Remove all references to the `avatar` from the API codebase (once 1 and 2 are done)

**Comment by timcowlishaw** [comment] 2023-10-26 06:29
Ok, i started working on (1) to see if i could find my way around the web-app and this has thrown up another interesting thing - it appears I'm getting hit by the rate limit when just browsing the site, and this is also causing images (and other things) not to load, which may also be causing problems!

**Comment by timcowlishaw** [comment] 2023-10-26 06:32
Yep, confirmed - i think this might be a more urgent thing to sort out - @oscgonfer we can chat this morning!

<img width="1796" alt="Screenshot 2023-10-26 at 08 31 02" src="https://github.com/fablabbcn/smartcitizen-api/assets/4279/cb5034fe-9b49-46c5-bea8-259d240cc2d7">

**Comment by timcowlishaw** [comment] 2023-10-26 10:08
Another possible related thing - some users raise an error for having a profile_picture blob without a `service_name` property. Worth investigating at the same time. This happens on this search on staging (But not locally, for some resason): https://staging-api.smartcitizen.me/v0/users?q%5Busername_cont%5D=team

**Comment by timcowlishaw** [comment] 2023-10-26 14:08
Sentry error for the above: https://iaac.sentry.io/issues/4576320257/?project=4506116341432320&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=1

**Comment by timcowlishaw** [comment] 2023-10-26 18:05
Ok, (2) above is deployed - i'll do (1) and (3) early next week!

**Comment by timcowlishaw** [comment] 2023-10-27 09:27
Once https://github.com/fablabbcn/smartcitizen-web/pull/448 and #277 are merged this should all work fine, and then i can get to work removing all trace of the old avatars from the api.

**Comment by oscgonfer** [comment] 2023-12-13 09:46
Closing as @timcowlishaw added this to the #286

**Closed by oscgonfer** 2023-12-13 09:46 UTC
Labels: bug
